version: '3.1'

services:
  diplomski:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=diplomski
    volumes:
      - ./import-catalog.sql:/docker-entrypoint-initdb.d/import-catalog.sql
    ports:
      - "3308:3306"
